name: mend


on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]


jobs:
  mend:
    runs-on: ubuntu-latest

    env:
      MEND_API_KEY : ${{secrets.MEND_API_KEY}}
      
    steps:
      - uses: actions/checkout@v3

      - name: run whitesource scan
        run: |

          set MAVEN_OPTS "-Xmx1024M -Xss128M -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=1024M -XX:+CMSClassUnloadingEnabled"
          
          curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar

          java -jar wss-unified-agent.jar -c wss-unified-agent.config wss.url https://shell.whitesourcesoftware.com/agent apiKey ${{ env.MEND_API_KEY }}
